apiVersion: apps/v1
kind: Deployment
metadata:
  name: and
spec:
  replicas: 1
  selector:
    matchLabels:
      app: and
  template:
    metadata:
      labels:
        app: and
    spec:
      containers:
      - image: okteto.dev/and:latest
        name: and
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "f6011358-2747-4dbb-a919-ee0b265648d7"
        - name: Vless_Path
          value: "/andinow"
        - name: Vmess_UUID
          value: "f6011358-2747-4dbb-a919-ee0b265648d7"
        - name: Vmess_Path
          value: "/howareyou"
        - name: Share_Path
          value: "$Share_Path"
